services:
  security-application-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ../pgdata:/var/lib/postgresql/data
    ports:
      - 5433:5432
volumes:
  pgdata: